# These defaults are meant for users and distro maintainers building from source, without intending to make multiple changes.
[build]
# Use a stage 1 build to make it faster. Stage 2 would be better eventually
build-stage = 1
test-stage = 1
doc-stage = 1
# When compiling from source, you usually want all tools.
extended = true

[llvm]
# Will download LLVM from CI if available on your platform.
download-ci-llvm = "if-available"
