# Adapted from https://github.com/rust-lang/rust/blob/master/src/bootstrap/defaults/config.user.toml

[build]
extended = true

# Use a stage 1 build to make it faster. Stage 2 would be better eventually
build-stage = 1
test-stage = 1
doc-stage = 1

[llvm]
download-ci-llvm = "if-available"
