# Defaults in https://github.com/rust-lang/rust/blob/master/src/bootstrap/defaults/config.user.toml
profile = "user"

[build]
# Use a stage 1 build to make it faster. Stage 2 would be better eventually
build-stage = 1
test-stage = 1
doc-stage = 1
dist-stage = 1
install-stage = 1

# Limited set of tools for now to speed up the build.
tools = ["cargo", "clippy", "rustfmt", "src"] 

[llvm]
download-ci-llvm = "if-available"
