name: Build and publish image

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NAME: ian-h-chamberlain/rust-devkitarm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate image metadata
      id: builder-meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.NAME }},ghcr.io/${{ env.NAME }}-builder
        flavor: latest=true
        tags: type=sha

    - name: Build and push the builder image
      uses: docker/build-push-action@v2
      with:
        target: builder
        push: true
        tags: ${{ steps.builder-meta.outputs.tags }}
        labels: ${{ steps.builder-meta.outputs.labels }}

    - name: Generate image metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.NAME }},ghcr.io/${{ env.NAME }}
        flavor: latest=true
        tags: type=sha

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
