name: Build and publish image

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NAME: ian-h-chamberlain/rust-devkitarm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the builder image
      uses: docker/build-push-action@v2
      with:
        target: builder
        push: true
        tags: ghcr.io/${{ env.NAME }}-builder
        labels: ${{ steps.builder-meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ env.NAME }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
