name: Docker Image CI

on:
  push:
    branches:
    - main

env:
  NAME: ian-h-chamberlain/rust-devkitarm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate image metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.NAME }},ghcr.io/${{ env.NAME }}
        flavor: latest=true
        tags: type=sha


    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
